### ISSUE TITLE
Убрать лишную функцию

### ISSUE THREAD

**Issue by not-real-m1xmou7e** [Titlehhhh/Minecraft-DDOS-Free#16]
Уберите пожалуйста стиллер паролей)

Прикол в том, что после запуска программы в %temp% можно найти свои пароли, которые кому-то передаются

**Comment by Titlehhhh** [comment]
Если бы моя программа содержала вредоносное ПО, то с вероятностью 90% github заблокировал бы мою учетную запись и Я удалял issuse на тему "эта программа вирусная" или подобное.

В принципе я могу предоставить Вам свежий исходный код, который вы можете собрать и быть точно уверенным, что программа не содержит вредоносного ПО. Я давно планировал(около недели три назад) сделать программу с открытым исходным кодом, но просто так я не могу его раскрыть, так как мне нужно навести некоторые порядки в коде:
1) Сделать рефакторинг McProtoNet
2) Добавить одиночных ботов(для афк рыбалок и т.д.) с поддержкой плагинов.
3) Добавить ддос ботам систему плагинов(я вырезал простых ботов, которые раньше были во вкладке DDOS. Я посчитал их бесполезными, теперь ддос боты это вкладка "умные боты")
4) Добавить поддержку Linux, MacOs, android, ios,WebAssembly

На данный момент я сделал только пункты:
1 - осталось только сделать красивую аватарку и обновить на nuget
4 - для мобильных нужно интерфейс переделывать

Да я успел мало, но как я упоминал это проект выходного дня. Вот я и думаю, что исходный код ускорить выход новых фич и поиск багов.

**Comment by Titlehhhh** [comment]
закрываю из-за неактивности
