### ISSUE TITLE
Дай свой телеграмм.

### ISSUE THREAD

**Issue by rwcv** [Titlehhhh/Minecraft-DDOS-Free#19]
Дай свой телеграмм для связи, или укажи его в профиле плиз :3

**Comment by Titlehhhh** [comment]
Когда я выпущу обновление, то в readme Я добавлю ссылку на Дискорд сервер

**Comment by rwcv** [comment]
> Когда я выпущу обновление, то в readme Я добавлю ссылку на Дискорд сервер

о, я думал ты забросил проект, но нет. ура!

**Comment by rwcv** [comment]
кстати, можешь дать сейчас? я бы тебе пару вопрос задал тут

**Comment by Titlehhhh** [comment]
Почему бы не задать эти пары вопросов здесь?

**Comment by rwcv** [comment]
Ну тогда эти пару вопросов. Что за плагины, где их взять и как их написать раз на то уже пошло. Как сделать похожий установщик? :D

**Comment by Titlehhhh** [comment]
Если вы имеете ввиду плагины в моем приложении, то они ещё пока не реализованы(посмотрите roadmap в readme). 

Про установщик. Ну в readme написано, что это clickonce. Вроде можно было загуглить. Но если вы не умеете, то вот ссылка: https://learn.microsoft.com/ru-ru/visualstudio/deployment/publishing-clickonce-applications?view=vs-2022

**Comment by rwcv** [comment]
не, я видел. просто как реализовано я не понял

**Comment by rwcv** [comment]
еще бы хотелось видеть прокси в проге
