### ISSUE TITLE
[Suggest] English or Chinese support

### ISSUE THREAD

**Issue by pthmz** [Titlehhhh/Minecraft-DDOS-Free#2]

**Comment by Titlehhhh** [comment]
First of all, I will add English. Chinese is probably not. I don't think online translators can accurately translate some words.

**Comment by pthmz** [comment]
Thank you very much, because I can't read Russian, I can read English.

**Comment by Titlehhhh** [comment]
The first time you can use https://www.deepl.com/translator . I will add support for at least English within 2-3 weeks. At the moment I am improving DDOS.

**Comment by Titlehhhh** [comment]
English is support!
