### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by MaicolFrantech** [Titlehhhh/Minecraft-DDOS-Free#3]
Здравствуйте, я хочу связаться с вами, чтобы продолжить пожертвования и продолжить финансирование этого проекта.

Hello, I want to contact you to continue donating and continue financing this project.

**Comment by Titlehhhh** [comment]
Заранее извиняюсь за то что поздно ответил, так как я был очень сильно занят эти две недели и не проверял почту. 

Что касается пожертвования, то мне нужно подумать. Этот проект не постоянный, так как я его делаю в свободное время. Можно сказать это проект выходного дня. Какой смысл финансировать проект, который в любой момент может застыть?

**Comment by MaicolFrantech** [comment]
Я так понимаю, что вы обновляете его только на досуге.  Это довольно
эффективный проект, насколько я его тестировал, и мне показалось хорошей
идеей помочь.

В любом случае спасибо за ваш ответ, и я надеюсь, что этот проект не
зависнет.
