### ISSUE TITLE
Нельзя установить!

### ISSUE THREAD

**Issue by ItsHamposter** [Titlehhhh/Minecraft-DDOS-Free#4]
СВЕДЕНИЯ О ВЕРСИИ ПЛАТФОРМЫ
	Windows 			: 10.0.19045.0 (Win32NT)
	Common Language Runtime 	: 4.0.30319.42000
	System.Deployment.dll 		: 4.8.4270.0 built by: NET48REL1LAST_C
	clr.dll 			: 4.8.4614.0 built by: NET48REL1LAST_B
	dfdll.dll 			: 4.8.4270.0 built by: NET48REL1LAST_C
	dfshim.dll 			: 10.0.19041.30000 (WinBuild.160101.0800)

ИСТОЧНИКИ
	URL-адрес развертывания			: https://raw.githubusercontent.com/Titlehhhh/Minecraft-DDOS-Free/master/published/McHolyBot.application
	URL-адрес поставщика развертывния		: https://raw.githubusercontent.com/Titlehhhh/Minecraft-DDOS-Free/master/published/McHolyBot.application
	URL-адрес приложения			: https://raw.githubusercontent.com/Titlehhhh/Minecraft-DDOS-Free/master/published/Application%20Files/McHolyBot_1_0_0_21/McHolyBot.dll.manifest

УДОСТОВЕРЕНИЯ
	Удостоверение развертывания		: McHolyBot.application, Version=1.0.0.21, Culture=neutral, PublicKeyToken=48175a927334850e, processorArchitecture=msil
	Удостоверение приложения		: McHolyBot.exe, Version=1.0.0.21, Culture=neutral, PublicKeyToken=48175a927334850e, processorArchitecture=msil, type=win32

СВОДКА ПРИЛОЖЕНИЯ
	* Устанавливаемое приложение.

СВОДКА ОШИБОК
	Ниже приводится сводка ошибок, сведения об этих ошибках перечислены далее в журнале.
	* В результате активизации https://raw.githubusercontent.com/Titlehhhh/Minecraft-DDOS-Free/master/published/McHolyBot.application произошла ошибка с исключением. Определены следующие сообщения о сбоях:
		+ Скачивание https://raw.githubusercontent.com/Titlehhhh/Minecraft-DDOS-Free/master/published/Application Files/McHolyBot_1_0_0_21/Microsoft.CodeAnalysis.dll.deploy не выполнено.
		+ Удаленный сервер возвратил ошибку: (503) Сервер не доступен.

СВОДКА СБОЯ ТРАНЗАКЦИИ СОХРАНЕНИЯ КОМПОНЕНТА
	Не определена никакая ошибка транзакции.

ПРЕДУПРЕЖДЕНИЯ
	Во время этой операции предупреждения не выводились.

СОСТОЯНИЕ ВЫПОЛНЕНИЯ ОПЕРАЦИИ
	* [09.04.2023 16:37:17] : Активация https://raw.githubusercontent.com/Titlehhhh/Minecraft-DDOS-Free/master/published/McHolyBot.application начата.
	* [09.04.2023 16:37:17] : Обработка манифеста развертывания успешно завершена.
	* [09.04.2023 16:37:17] : Начата установка приложения.
	* [09.04.2023 16:37:17] : Обработка манифеста приложения успешно завершена.
	* [09.04.2023 16:37:20] : Найдена совместимая версия среды выполнения 4.0.30319.
	* [09.04.2023 16:37:20] : Запрос доверительных отношений и определение платформы завершены.

СВЕДЕНИЯ ОБ ОШИБКЕ
	Во время выполнения этой операции обнаружены следующие ошибки.
	* [09.04.2023 16:37:39] System.Deployment.Application.DeploymentDownloadException (Неизвестный подтип)
		- Скачивание https://raw.githubusercontent.com/Titlehhhh/Minecraft-DDOS-Free/master/published/Application Files/McHolyBot_1_0_0_21/Microsoft.CodeAnalysis.dll.deploy не выполнено.
		- Источник: System.Deployment
		- Запись изменений стека:
			в System.Deployment.Application.SystemNetDownloader.DownloadSingleFile(DownloadQueueItem next)
			в System.Deployment.Application.SystemNetDownloader.DownloadAllFiles()
			в System.Deployment.Application.FileDownloader.Download(SubscriptionState subState, X509Certificate2 clientCertificate)
			в System.Deployment.Application.DownloadManager.DownloadDependencies(SubscriptionState subState, AssemblyManifest deployManifest, AssemblyManifest appManifest, Uri sourceUriBase, String targetDirectory, String group, IDownloadNotification notification, DownloadOptions options)
			в System.Deployment.Application.ApplicationActivator.DownloadApplication(SubscriptionState subState, ActivationDescription actDesc, Int64 transactionId, TempDirectory& downloadTemp)
			в System.Deployment.Application.ApplicationActivator.InstallApplication(SubscriptionState& subState, ActivationDescription actDesc)
			в System.Deployment.Application.ApplicationActivator.PerformDeploymentActivation(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl, Uri& deploymentUri)
			в System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
			в System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
			в System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
			в System.Deployment.Application.ApplicationActivator.ActivateDeploymentWorker(Object state)
		--- Внутреннее исключение ---
		System.Net.WebException
		- Удаленный сервер возвратил ошибку: (503) Сервер не доступен.
		- Источник: System
		- Запись изменений стека:
			в System.Net.HttpWebRequest.GetResponse()
			в System.Deployment.Application.SystemNetDownloader.DownloadSingleFile(DownloadQueueItem next)

СВЕДЕНИЯ О ТРАНЗАКЦИИ СОХРАНЕНИЯ КОМПОНЕНТА
	Нет доступных сведений о транзакции.

**Comment by Titlehhhh** [comment]
Оохх блин я давно не проверял почту так как был очень сильно занят. Попробуйте удалить и заново установить приложение. Если это не поможет, то будем решать дальше
