### ISSUE TITLE
Крашит...

### ISSUE THREAD

**Issue by GHOUL10007** [Titlehhhh/Minecraft-DDOS-Free#6]
Открываю прогу и через полторы секунды крашит/зависает и крашит когда как. 
Файл с ошибками приложил
[errors.txt](https://github.com/Titlehhhh/Minecraft-DDOS-Free/files/11350381/errors.txt)

**Comment by Titlehhhh** [comment]
Мне у себя удалось воспроизвести проблему и решить её. В ближайшее 5 дней я выпущу версию 1.0.0.22, которая решит проблему. Да это не быстро так как этот проект у меня не один.

Эта проблема была из-за какой то библиотеки для решения каптч.
