### ISSUE TITLE
Add English/Chinese Version

### ISSUE THREAD

**Issue by Starry-Sky-World** [Titlehhhh/Minecraft-DDOS-Free#65]
Please.

**Comment by Titlehhhh** [comment]
I have English language support. However, in some places I forgot to translate.....

**Comment by Titlehhhh** [comment]
Chinese I'm unlikely to support because I'm not a native speaker of the language, nor do I have native speaker acquaintances, nor do I have the money for a professional translator.

**Comment by Starry-Sky-World** [comment]
我可以试试
I want to do.
but I'm pupil.(12 year's old, CHN)

**Comment by Titlehhhh** [comment]
When I release the next version, I will write to you

**Comment by Starry-Sky-World** [comment]
> When I release the next version, I will write to you当我发布下一个版本时，我会写信给你

Okay
