### ISSUE TITLE
Program is crashing after launch 

### ISSUE THREAD

**Issue by WataLaker37821** [Titlehhhh/Minecraft-DDOS-Free#7]
Once i will open it, it will show the bots page (without loading any lines) and crash right after that.
[errors.txt](https://github.com/Titlehhhh/Minecraft-DDOS-Free/files/11354825/errors.txt)
Last error is right one

**Comment by WataLaker37821** [comment]
извините, посмотрел, увидел что уже видимо был похожий баг, а также понял что можно и на русском писать )

**Comment by Titlehhhh** [comment]
Обновление исправило проблему
