### ISSUE TITLE
не работает 

### ISSUE THREAD

**Issue by dimiprimi228** [Titlehhhh/Minecraft-DDOS-Free#8]
на скрине пишет не скачивает так как нету файлы
![image](https://user-images.githubusercontent.com/111719163/235349934-4e31045c-0cc5-499c-9ba5-16de046ff6be.png)

**Comment by Titlehhhh** [comment]
Немножко нужно потерпеть, буквально день или полтора дня. Я сейчас в системе установки делаю некоторые изменения. Как только сделаю напишу в этом коммите

**Comment by dimiprimi228** [comment]
хорошо бес проблем буду рад обновлению спасибо за такую крутую программу и если сможешь добавить  все версии 1.19 1.20
будет круто 
спасибо )
и было бы славно если боты умели ходить или ты пишешь свой или чужой ник  то за ним было ходили боты было бы очень круто я много прошу ну просто даю идеи для ботов твоё решение добавлять или нет

**Comment by tanishisherewithhh** [comment]
Все, что я хочу сказать, это то, что спасибо, Titlehhhh
за создание этого шедевра и его бесплатную публикацию. Программа работает красиво, как произведение искусства. Хотя я надеюсь, что поддержка скрипта для перемещения и текстовых сообщений будет добавлена в ближайшее время. Я надеюсь, что Бог даст вам мир. Кроме того, я написал это с помощью гугл-переводчика, так что извините, если что-то пойдет не так.

**Comment by dimiprimi228** [comment]
Ну что когда там уже заработает

**Comment by Titlehhhh** [comment]
Я выпустил обновление 1.0.0.23, которое исправило проблему. Если вдруг возникнут опять проблемы то пишите сюда

**Comment by dimiprimi228** [comment]
спасибо все работает
